# Generated by Django 2.2 on 2021-05-04 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notify',
        ),
    ]
